# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DreamGame' do
  pod 'CHCSVParser', '~> 2.1'
end

target 'DreamGameTests' do

end

